# Sheet 2 - Policy
# (id, category, channel, os, what_to_test, tier)
# One row per channel PER OPERATING SYSTEM. Not every channel exists on every OS, and
# maturity genuinely differs - USB write is table stakes on Windows, advanced on Linux.
# The Monitor / Warn / Block result columns are left blank for the tester.

GEN   = "GenAI & AI Tools"
MAIL  = "Webmail & Messaging"
CLOUD = "Cloud Storage & File Transfer"
BROW  = "Browsers"
PHYS  = "Physical & Local Device"
NET   = "Network & Remote Access"

POLICY = [
# ------------------------------------------------------------ GEN
("P-G01.Windows", GEN, "GenAI web chat - paste into prompt", "Windows",
 "Paste 30 SSNs into ChatGPT / Claude / Gemini / Copilot in the managed browser. Then repeat with a block of text copied out of a file the tool already classifies as sensitive, and note whether the tool judges the pasted text on its own or carries over what it knew about the source file.",
 "Table stakes"),
("P-G01.macOS", GEN, "GenAI web chat - paste into prompt", "macOS",
 "Paste 30 SSNs into ChatGPT / Claude / Gemini / Copilot in the managed browser. Then repeat with a block of text copied out of a file the tool already classifies as sensitive, and note whether the tool judges the pasted text on its own or carries over what it knew about the source file.",
 "Advanced"),
("P-G01.Linux", GEN, "GenAI web chat - paste into prompt", "Linux",
 "Paste 30 SSNs into ChatGPT / Claude / Gemini / Copilot in the managed browser. Then repeat with a block of text copied out of a file the tool already classifies as sensitive, and note whether the tool judges the pasted text on its own or carries over what it knew about the source file.",
 "Differentiator"),
("P-G02.Windows", GEN, "GenAI web chat - file upload / attachment", "Windows",
 "Attach a .csv of customer records to a prompt, then repeat with a .png of the same data to exercise the OCR path. Note whether upload is covered by the same rule as the paste test or a separate one.",
 "Table stakes"),
("P-G02.macOS", GEN, "GenAI web chat - file upload / attachment", "macOS",
 "Attach a .csv of customer records to a prompt, then repeat with a .png of the same data to exercise the OCR path. Note whether upload is covered by the same rule as the paste test or a separate one.",
 "Table stakes"),
("P-G02.Linux", GEN, "GenAI web chat - file upload / attachment", "Linux",
 "Attach a .csv of customer records to a prompt, then repeat with a .png of the same data to exercise the OCR path. Note whether upload is covered by the same rule as the paste test or a separate one.",
 "Differentiator"),
("P-G03.Windows", GEN, "GenAI desktop apps (ChatGPT, Claude, Copilot)", "Windows",
 "Put the same content through the native desktop app rather than the browser. Note whether coverage comes from a browser or domain rule - which will not apply here - or from restricted-app or process-level control.",
 "Advanced"),
("P-G03.macOS", GEN, "GenAI desktop apps (ChatGPT, Claude, Copilot)", "macOS",
 "Put the same content through the native desktop app rather than the browser. Note whether coverage comes from a browser or domain rule - which will not apply here - or from restricted-app or process-level control.",
 "Advanced"),
("P-G04.Windows", GEN, "AI coding assistants in the IDE (Copilot, Cursor, Windsurf, Claude Code)", "Windows",
 "Open a file containing proprietary code and an API key, let the assistant index the workspace, and accept an inline completion. Then put the same content through a browser chat window and through a terminal AI CLI, and compare what each of the three records. The IDE reads files directly and streams context, so there is no upload event to intercept - the gap between three routes to the same model is the finding.",
 "Differentiator"),
("P-G04.macOS", GEN, "AI coding assistants in the IDE (Copilot, Cursor, Windsurf, Claude Code)", "macOS",
 "Open a file containing proprietary code and an API key, let the assistant index the workspace, and accept an inline completion. Then put the same content through a browser chat window and through a terminal AI CLI, and compare what each of the three records. The IDE reads files directly and streams context, so there is no upload event to intercept - the gap between three routes to the same model is the finding.",
 "Differentiator"),
("P-G04.Linux", GEN, "AI coding assistants in the IDE (Copilot, Cursor, Windsurf, Claude Code)", "Linux",
 "Open a file containing proprietary code and an API key, let the assistant index the workspace, and accept an inline completion. Then put the same content through a browser chat window and through a terminal AI CLI, and compare what each of the three records. The IDE reads files directly and streams context, so there is no upload event to intercept - the gap between three routes to the same model is the finding.",
 "Differentiator"),
("P-G05.Windows", GEN, "AI CLI tools and MCP servers reading local files", "Windows",
 "Run an AI CLI in a directory of sensitive files, and connect an MCP server with filesystem access. Detection here depends on process-level file-access monitoring rather than network egress, so confirm which one the tool is doing.",
 "Differentiator"),
("P-G05.macOS", GEN, "AI CLI tools and MCP servers reading local files", "macOS",
 "Run an AI CLI in a directory of sensitive files, and connect an MCP server with filesystem access. Detection here depends on process-level file-access monitoring rather than network egress, so confirm which one the tool is doing.",
 "Differentiator"),
("P-G05.Linux", GEN, "AI CLI tools and MCP servers reading local files", "Linux",
 "Run an AI CLI in a directory of sensitive files, and connect an MCP server with filesystem access. Detection here depends on process-level file-access monitoring rather than network egress, so confirm which one the tool is doing.",
 "Differentiator"),
("P-G06.Windows", GEN, "Agentic browsers (Comet, Atlas, Dia) acting autonomously", "Windows",
 "Ask the browser agent to summarise a sensitive local file and send the summary somewhere. Check whether the incident attributes the action to the user or to the browser process - the agent, not the person, performed the egress.",
 "Differentiator"),
("P-G06.macOS", GEN, "Agentic browsers (Comet, Atlas, Dia) acting autonomously", "macOS",
 "Ask the browser agent to summarise a sensitive local file and send the summary somewhere. Check whether the incident attributes the action to the user or to the browser process - the agent, not the person, performed the egress.",
 "Differentiator"),
("P-G07.Windows", GEN, "Meeting assistants and transcription bots", "Windows",
 "Join a call with a third-party notetaker recording, and screen-share a sensitive document. This is screen content rather than a file, so note whether it is covered by screen-capture control or not at all.",
 "Differentiator"),
("P-G07.macOS", GEN, "Meeting assistants and transcription bots", "macOS",
 "Join a call with a third-party notetaker recording, and screen-share a sensitive document. This is screen content rather than a file, so note whether it is covered by screen-capture control or not at all.",
 "Differentiator"),
("P-G08.Windows", GEN, "Shadow AI discovery", "Windows",
 "Over a two-week pilot, list every AI destination users actually reached. Ask for the list the tool discovered, not the list it ships with - a static list of known AI domains goes stale within weeks.",
 "Advanced"),
("P-G08.macOS", GEN, "Shadow AI discovery", "macOS",
 "Over a two-week pilot, list every AI destination users actually reached. Ask for the list the tool discovered, not the list it ships with - a static list of known AI domains goes stale within weeks.",
 "Advanced"),
("P-G08.Linux", GEN, "Shadow AI discovery", "Linux",
 "Over a two-week pilot, list every AI destination users actually reached. Ask for the list the tool discovered, not the list it ships with - a static list of known AI domains goes stale within weeks.",
 "Differentiator"),
# ------------------------------------------------------------ MAIL
("P-M01.Windows", MAIL, "Personal webmail - paste into the body", "Windows",
 "Paste 30 SSNs into a Gmail / Outlook.com / Proton compose window. Note whether body paste and attachment upload are one rule or two.",
 "Table stakes"),
("P-M01.macOS", MAIL, "Personal webmail - paste into the body", "macOS",
 "Paste 30 SSNs into a Gmail / Outlook.com / Proton compose window. Note whether body paste and attachment upload are one rule or two.",
 "Advanced"),
("P-M01.Linux", MAIL, "Personal webmail - paste into the body", "Linux",
 "Paste 30 SSNs into a Gmail / Outlook.com / Proton compose window. Note whether body paste and attachment upload are one rule or two.",
 "Differentiator"),
("P-M02.Windows", MAIL, "Personal webmail - attachment upload", "Windows",
 "Attach a sensitive .xlsx to a personal webmail draft. Check whether the draft auto-save uploads the file before your policy has finished evaluating it.",
 "Table stakes"),
("P-M02.macOS", MAIL, "Personal webmail - attachment upload", "macOS",
 "Attach a sensitive .xlsx to a personal webmail draft. Check whether the draft auto-save uploads the file before your policy has finished evaluating it.",
 "Table stakes"),
("P-M02.Linux", MAIL, "Personal webmail - attachment upload", "Linux",
 "Attach a sensitive .xlsx to a personal webmail draft. Check whether the draft auto-save uploads the file before your policy has finished evaluating it.",
 "Differentiator"),
("P-M03.Windows", MAIL, "Corporate mail client to an external recipient", "Windows",
 "Send a sensitive attachment from Outlook desktop to a personal address. Confirm you get one incident rather than two - endpoint and mail-gateway DLP may both fire.",
 "Table stakes"),
("P-M03.macOS", MAIL, "Corporate mail client to an external recipient", "macOS",
 "Send a sensitive attachment from Outlook desktop to a personal address. Confirm you get one incident rather than two - endpoint and mail-gateway DLP may both fire.",
 "Table stakes"),
("P-M03.Linux", MAIL, "Corporate mail client to an external recipient", "Linux",
 "Send a sensitive attachment from Outlook desktop to a personal address. Confirm you get one incident rather than two - endpoint and mail-gateway DLP may both fire.",
 "Differentiator"),
("P-M04.Windows", MAIL, "Consumer messaging web (WhatsApp Web, Telegram, Signal)", "Windows",
 "Send a sensitive file and a pasted block of PII through each, in the browser and again in the desktop client. Transport is encrypted, so only the endpoint can see this, and the desktop client needs separate app-level control.",
 "Advanced"),
("P-M04.macOS", MAIL, "Consumer messaging web (WhatsApp Web, Telegram, Signal)", "macOS",
 "Send a sensitive file and a pasted block of PII through each, in the browser and again in the desktop client. Transport is encrypted, so only the endpoint can see this, and the desktop client needs separate app-level control.",
 "Advanced"),
("P-M04.Linux", MAIL, "Consumer messaging web (WhatsApp Web, Telegram, Signal)", "Linux",
 "Send a sensitive file and a pasted block of PII through each, in the browser and again in the desktop client. Transport is encrypted, so only the endpoint can see this, and the desktop client needs separate app-level control.",
 "Differentiator"),
("P-M05.Windows", MAIL, "Collaboration apps - external and guest channels", "Windows",
 "Post a sensitive file to a Slack Connect channel and a Teams external chat, then post the same file to an internal channel as a control. Internal and external destinations look identical to the agent unless it can read the channel context.",
 "Differentiator"),
("P-M05.macOS", MAIL, "Collaboration apps - external and guest channels", "macOS",
 "Post a sensitive file to a Slack Connect channel and a Teams external chat, then post the same file to an internal channel as a control. Internal and external destinations look identical to the agent unless it can read the channel context.",
 "Differentiator"),
("P-M05.Linux", MAIL, "Collaboration apps - external and guest channels", "Linux",
 "Post a sensitive file to a Slack Connect channel and a Teams external chat, then post the same file to an internal channel as a control. Internal and external destinations look identical to the agent unless it can read the channel context.",
 "Differentiator"),
("P-M06.macOS", MAIL, "macOS Messages / iMessage relay", "macOS",
 "Send a sensitive file from Messages on a Mac. Note whether it is covered at all, or only by a restricted-app policy.",
 "Differentiator"),
# ------------------------------------------------------------ CLOUD
("P-C01.Windows", CLOUD, "Personal cloud storage - web upload", "Windows",
 "Upload a sensitive file to personal Dropbox / Google Drive / OneDrive / Box / iCloud in the browser. This is the baseline - if it fails, stop and fix the deployment before running anything else on this sheet.",
 "Table stakes"),
("P-C01.macOS", CLOUD, "Personal cloud storage - web upload", "macOS",
 "Upload a sensitive file to personal Dropbox / Google Drive / OneDrive / Box / iCloud in the browser. This is the baseline - if it fails, stop and fix the deployment before running anything else on this sheet.",
 "Table stakes"),
("P-C01.Linux", CLOUD, "Personal cloud storage - web upload", "Linux",
 "Upload a sensitive file to personal Dropbox / Google Drive / OneDrive / Box / iCloud in the browser. This is the baseline - if it fails, stop and fix the deployment before running anything else on this sheet.",
 "Advanced"),
("P-C02.Windows", CLOUD, "Cloud sync client (desktop agent, not the browser)", "Windows",
 "Drop the same file into a synced folder on disk, with no browser involved, and confirm it produces the same result as the web upload. This is the most commonly missed variant of the most commonly tested channel.",
 "Table stakes"),
("P-C02.macOS", CLOUD, "Cloud sync client (desktop agent, not the browser)", "macOS",
 "Drop the same file into a synced folder on disk, with no browser involved, and confirm it produces the same result as the web upload. This is the most commonly missed variant of the most commonly tested channel.",
 "Table stakes"),
("P-C02.Linux", CLOUD, "Cloud sync client (desktop agent, not the browser)", "Linux",
 "Drop the same file into a synced folder on disk, with no browser involved, and confirm it produces the same result as the web upload. This is the most commonly missed variant of the most commonly tested channel.",
 "Differentiator"),
("P-C03.Windows", CLOUD, "Personal account inside a sanctioned service", "Windows",
 "Sign in to a personal Google or Microsoft account alongside the corporate tenant and upload there. The domain is allow-listed, so a domain rule will pass it - check whether tenant or account-level restriction is available.",
 "Differentiator"),
("P-C03.macOS", CLOUD, "Personal account inside a sanctioned service", "macOS",
 "Sign in to a personal Google or Microsoft account alongside the corporate tenant and upload there. The domain is allow-listed, so a domain rule will pass it - check whether tenant or account-level restriction is available.",
 "Differentiator"),
("P-C03.Linux", CLOUD, "Personal account inside a sanctioned service", "Linux",
 "Sign in to a personal Google or Microsoft account alongside the corporate tenant and upload there. The domain is allow-listed, so a domain rule will pass it - check whether tenant or account-level restriction is available.",
 "Differentiator"),
("P-C04.Windows", CLOUD, "Anonymous file transfer and paste sites", "Windows",
 "Upload to WeTransfer and file.io, and paste to Pastebin and a public GitHub Gist. Then test a site that is NOT on the vendor's list, to see the default behaviour for unknown destinations.",
 "Advanced"),
("P-C04.macOS", CLOUD, "Anonymous file transfer and paste sites", "macOS",
 "Upload to WeTransfer and file.io, and paste to Pastebin and a public GitHub Gist. Then test a site that is NOT on the vendor's list, to see the default behaviour for unknown destinations.",
 "Advanced"),
("P-C04.Linux", CLOUD, "Anonymous file transfer and paste sites", "Linux",
 "Upload to WeTransfer and file.io, and paste to Pastebin and a public GitHub Gist. Then test a site that is NOT on the vendor's list, to see the default behaviour for unknown destinations.",
 "Differentiator"),
("P-C05.Windows", CLOUD, "FTP / SFTP / SCP client", "Windows",
 "Upload a sensitive file to ftp.dlptest.com (credentials on dlptest.com/ftp-test/), then repeat over SFTP and compare. Cleartext FTP should be trivially inspectable; SFTP is encrypted and needs endpoint visibility.",
 "Table stakes"),
("P-C05.macOS", CLOUD, "FTP / SFTP / SCP client", "macOS",
 "Upload a sensitive file to ftp.dlptest.com (credentials on dlptest.com/ftp-test/), then repeat over SFTP and compare. Cleartext FTP should be trivially inspectable; SFTP is encrypted and needs endpoint visibility.",
 "Advanced"),
("P-C05.Linux", CLOUD, "FTP / SFTP / SCP client", "Linux",
 "Upload a sensitive file to ftp.dlptest.com (credentials on dlptest.com/ftp-test/), then repeat over SFTP and compare. Cleartext FTP should be trivially inspectable; SFTP is encrypted and needs endpoint visibility.",
 "Advanced"),
("P-C06.Windows", CLOUD, "HTTP and HTTPS POST to an arbitrary endpoint", "Windows",
 "Post sample data to dlptest.com/http-post/ and dlptest.com/https-post/, first from the browser and then from curl, and compare. The browser case usually works; the curl case is the real test of process-level coverage. Then repeat with a large file over the S3 target on dlptest.com/ftp-test/, to confirm the tool inspects chunked multipart uploads and not just simple form posts.",
 "Table stakes"),
("P-C06.macOS", CLOUD, "HTTP and HTTPS POST to an arbitrary endpoint", "macOS",
 "Post sample data to dlptest.com/http-post/ and dlptest.com/https-post/, first from the browser and then from curl, and compare. The browser case usually works; the curl case is the real test of process-level coverage. Then repeat with a large file over the S3 target on dlptest.com/ftp-test/, to confirm the tool inspects chunked multipart uploads and not just simple form posts.",
 "Table stakes"),
("P-C06.Linux", CLOUD, "HTTP and HTTPS POST to an arbitrary endpoint", "Linux",
 "Post sample data to dlptest.com/http-post/ and dlptest.com/https-post/, first from the browser and then from curl, and compare. The browser case usually works; the curl case is the real test of process-level coverage. Then repeat with a large file over the S3 target on dlptest.com/ftp-test/, to confirm the tool inspects chunked multipart uploads and not just simple form posts.",
 "Advanced"),
("P-C07.Windows", CLOUD, "Git push to a personal or unknown remote", "Windows",
 "Push the same repository three times: to the corporate GitHub org, to a personal GitHub account, then to an unknown third-party remote. Put a file containing an API key in it so there is content to match on as well as a destination to judge. The content is identical in all three - only the destination differs, and the corporate push must pass silently.",
 "Differentiator"),
("P-C07.macOS", CLOUD, "Git push to a personal or unknown remote", "macOS",
 "Push the same repository three times: to the corporate GitHub org, to a personal GitHub account, then to an unknown third-party remote. Put a file containing an API key in it so there is content to match on as well as a destination to judge. The content is identical in all three - only the destination differs, and the corporate push must pass silently.",
 "Differentiator"),
("P-C07.Linux", CLOUD, "Git push to a personal or unknown remote", "Linux",
 "Push the same repository three times: to the corporate GitHub org, to a personal GitHub account, then to an unknown third-party remote. Put a file containing an API key in it so there is content to match on as well as a destination to judge. The content is identical in all three - only the destination differs, and the corporate push must pass silently.",
 "Differentiator"),
("P-C08.Windows", CLOUD, "Object storage CLI (aws s3 cp, gsutil, azcopy)", "Windows",
 "Copy a sensitive file to a personal S3 bucket from the terminal. Confirm the agent attributes it to the process, not just to a destination.",
 "Differentiator"),
("P-C08.macOS", CLOUD, "Object storage CLI (aws s3 cp, gsutil, azcopy)", "macOS",
 "Copy a sensitive file to a personal S3 bucket from the terminal. Confirm the agent attributes it to the process, not just to a destination.",
 "Differentiator"),
("P-C08.Linux", CLOUD, "Object storage CLI (aws s3 cp, gsutil, azcopy)", "Linux",
 "Copy a sensitive file to a personal S3 bucket from the terminal. Confirm the agent attributes it to the process, not just to a destination.",
 "Differentiator"),
# ------------------------------------------------------------ BROW
("P-B01.Windows", BROW, "Unmanaged / shadow browsers (Brave, Vivaldi, Opera, Tor)", "Windows",
 "Install Brave (or Vivaldi, or a Tor Browser build). Through it, upload a file of sample PII to a personal Dropbox or Google Drive account, then paste 30 SSNs into a GenAI chat window. Note whether you get inspection, a wholesale block, or nothing - there is rarely a middle ground.",
 "Table stakes"),
("P-B01.macOS", BROW, "Unmanaged / shadow browsers (Brave, Vivaldi, Opera, Tor)", "macOS",
 "Install Brave (or Vivaldi, or a Tor Browser build). Through it, upload a file of sample PII to a personal Dropbox or Google Drive account, then paste 30 SSNs into a GenAI chat window. Note whether you get inspection, a wholesale block, or nothing - there is rarely a middle ground.",
 "Advanced"),
("P-B01.Linux", BROW, "Unmanaged / shadow browsers (Brave, Vivaldi, Opera, Tor)", "Linux",
 "Install Brave (or Vivaldi, or a Tor Browser build). Through it, upload a file of sample PII to a personal Dropbox or Google Drive account, then paste 30 SSNs into a GenAI chat window. Note whether you get inspection, a wholesale block, or nothing - there is rarely a middle ground.",
 "Differentiator"),
("P-B02.Windows", BROW, "Private / incognito mode", "Windows",
 "Open an incognito or private window and upload a file of sample PII to a personal cloud storage account. Check first whether your DLP browser extension is permitted to run in private windows - by default most are not.",
 "Table stakes"),
("P-B02.macOS", BROW, "Private / incognito mode", "macOS",
 "Open an incognito or private window and upload a file of sample PII to a personal cloud storage account. Check first whether your DLP browser extension is permitted to run in private windows - by default most are not.",
 "Table stakes"),
("P-B02.Linux", BROW, "Private / incognito mode", "Linux",
 "Open an incognito or private window and upload a file of sample PII to a personal cloud storage account. Check first whether your DLP browser extension is permitted to run in private windows - by default most are not.",
 "Differentiator"),
("P-B03.Windows", BROW, "Personal browser profile", "Windows",
 "Create a second Chrome profile signed in to a personal account and upload from it. Enforcement is often per-profile, so confirm the second profile is covered.",
 "Advanced"),
("P-B03.macOS", BROW, "Personal browser profile", "macOS",
 "Create a second Chrome profile signed in to a personal account and upload from it. Enforcement is often per-profile, so confirm the second profile is covered.",
 "Advanced"),
("P-B03.Linux", BROW, "Personal browser profile", "Linux",
 "Create a second Chrome profile signed in to a personal account and upload from it. Enforcement is often per-profile, so confirm the second profile is covered.",
 "Differentiator"),
("P-B04.Windows", BROW, "Portable browser run from USB", "Windows",
 "Run a portable Firefox or Chromium from a USB stick with no install. No install means no extension and no managed policy, so this needs process-level blocking by hash or path.",
 "Differentiator"),
("P-B04.macOS", BROW, "Portable browser run from USB", "macOS",
 "Run a portable Firefox or Chromium from a USB stick with no install. No install means no extension and no managed policy, so this needs process-level blocking by hash or path.",
 "Differentiator"),
("P-B04.Linux", BROW, "Portable browser run from USB", "Linux",
 "Run a portable Firefox or Chromium from a USB stick with no install. No install means no extension and no managed policy, so this needs process-level blocking by hash or path.",
 "Differentiator"),
# ------------------------------------------------------------ PHYS
("P-P01.Windows", PHYS, "USB mass storage write", "Windows",
 "Copy a sensitive file to a USB drive. Then open the file from a network location and Save As directly to the USB. The second variant is the one that matters: if data is never written to local disk first, many endpoint agents cannot classify it at all.",
 "Table stakes"),
("P-P01.macOS", PHYS, "USB mass storage write", "macOS",
 "Copy a sensitive file to a USB drive. Then open the file from a network location and Save As directly to the USB. The second variant is the one that matters: if data is never written to local disk first, many endpoint agents cannot classify it at all.",
 "Table stakes"),
("P-P01.Linux", PHYS, "USB mass storage write", "Linux",
 "Copy a sensitive file to a USB drive. Then open the file from a network location and Save As directly to the USB. The second variant is the one that matters: if data is never written to local disk first, many endpoint agents cannot classify it at all.",
 "Advanced"),
("P-P02.Windows", PHYS, "MTP / PTP devices (phones, cameras)", "Windows",
 "Copy a sensitive file to an iPhone or Android device over USB. MTP is not mass storage, so a USB rule may not fire at all.",
 "Advanced"),
("P-P02.macOS", PHYS, "MTP / PTP devices (phones, cameras)", "macOS",
 "Copy a sensitive file to an iPhone or Android device over USB. MTP is not mass storage, so a USB rule may not fire at all.",
 "Advanced"),
("P-P02.Linux", PHYS, "MTP / PTP devices (phones, cameras)", "Linux",
 "Copy a sensitive file to an iPhone or Android device over USB. MTP is not mass storage, so a USB rule may not fire at all.",
 "Differentiator"),
("P-P03.Windows", PHYS, "Bluetooth file transfer", "Windows",
 "Send a sensitive file over Bluetooth to a phone or laptop. Note whether it is enforced as a channel or as an unallowed-app list.",
 "Advanced"),
("P-P03.macOS", PHYS, "Bluetooth file transfer", "macOS",
 "Send a sensitive file over Bluetooth to a phone or laptop. Note whether it is enforced as a channel or as an unallowed-app list.",
 "Advanced"),
("P-P03.Linux", PHYS, "Bluetooth file transfer", "Linux",
 "Send a sensitive file over Bluetooth to a phone or laptop. Note whether it is enforced as a channel or as an unallowed-app list.",
 "Differentiator"),
("P-P04.macOS", PHYS, "AirDrop (macOS)", "macOS",
 "AirDrop a sensitive file to a nearby personal device. Peer to peer with no network hop - ask the vendor directly, since support is inconsistent and often newer than the datasheet.",
 "Differentiator"),
("P-P05.Windows", PHYS, "Print to a local printer", "Windows",
 "Print a document containing 50 SSNs. Confirm the incident records the printer name and the page count.",
 "Table stakes"),
("P-P05.macOS", PHYS, "Print to a local printer", "macOS",
 "Print a document containing 50 SSNs. Confirm the incident records the printer name and the page count.",
 "Table stakes"),
("P-P05.Linux", PHYS, "Print to a local printer", "Linux",
 "Print a document containing 50 SSNs. Confirm the incident records the printer name and the page count.",
 "Advanced"),
("P-P06.Windows", PHYS, "Print to PDF / print to file", "Windows",
 "Use 'Microsoft Print to PDF' or the macOS Save as PDF option. Test each print sub-feature separately rather than assuming print is one control - this is an export rather than a print, and is frequently uncontrolled.",
 "Advanced"),
("P-P06.macOS", PHYS, "Print to PDF / print to file", "macOS",
 "Use 'Microsoft Print to PDF' or the macOS Save as PDF option. Test each print sub-feature separately rather than assuming print is one control - this is an export rather than a print, and is frequently uncontrolled.",
 "Advanced"),
("P-P06.Linux", PHYS, "Print to PDF / print to file", "Linux",
 "Use 'Microsoft Print to PDF' or the macOS Save as PDF option. Test each print sub-feature separately rather than assuming print is one control - this is an export rather than a print, and is frequently uncontrolled.",
 "Differentiator"),
("P-P07.Windows", PHYS, "Network and shared printers", "Windows",
 "Print to a shared queue and to a printer on a different subnet. Confirm you can allow the corporate queue and restrict everything else.",
 "Advanced"),
("P-P07.macOS", PHYS, "Network and shared printers", "macOS",
 "Print to a shared queue and to a printer on a different subnet. Confirm you can allow the corporate queue and restrict everything else.",
 "Advanced"),
("P-P07.Linux", PHYS, "Network and shared printers", "Linux",
 "Print to a shared queue and to a printer on a different subnet. Confirm you can allow the corporate queue and restrict everything else.",
 "Differentiator"),
("P-P08.Windows", PHYS, "Screen capture (snipping tool, Cmd-Shift-4, Print Screen)", "Windows",
 "Screenshot a screen full of PII, save it, then upload it. There are two separate controls here - preventing the capture, and detecting the resulting image. Note which you get.",
 "Advanced"),
("P-P08.macOS", PHYS, "Screen capture (snipping tool, Cmd-Shift-4, Print Screen)", "macOS",
 "Screenshot a screen full of PII, save it, then upload it. There are two separate controls here - preventing the capture, and detecting the resulting image. Note which you get.",
 "Advanced"),
("P-P08.Linux", PHYS, "Screen capture (snipping tool, Cmd-Shift-4, Print Screen)", "Linux",
 "Screenshot a screen full of PII, save it, then upload it. There are two separate controls here - preventing the capture, and detecting the resulting image. Note which you get.",
 "Differentiator"),
("P-P09.Windows", PHYS, "Clipboard copy into a non-sanctioned app", "Windows",
 "Copy from a document containing 30 SSNs into Notepad, then into a chat app, then into another document. Note intra-app versus inter-app behaviour - many tools allow copy and paste within one application family and block it across.",
 "Table stakes"),
("P-P09.macOS", PHYS, "Clipboard copy into a non-sanctioned app", "macOS",
 "Copy from a document containing 30 SSNs into Notepad, then into a chat app, then into another document. Note intra-app versus inter-app behaviour - many tools allow copy and paste within one application family and block it across.",
 "Advanced"),
("P-P09.Linux", PHYS, "Clipboard copy into a non-sanctioned app", "Linux",
 "Copy from a document containing 30 SSNs into Notepad, then into a chat app, then into another document. Note intra-app versus inter-app behaviour - many tools allow copy and paste within one application family and block it across.",
 "Differentiator"),
("P-P10.Windows", PHYS, "Retyping / manual transcription", "Windows",
 "Read PII off the screen and type it into an unmonitored form. Expect nothing to catch this: record it as accepted residual risk rather than leaving the row blank.",
 "Differentiator"),
("P-P10.macOS", PHYS, "Retyping / manual transcription", "macOS",
 "Read PII off the screen and type it into an unmonitored form. Expect nothing to catch this: record it as accepted residual risk rather than leaving the row blank.",
 "Differentiator"),
("P-P10.Linux", PHYS, "Retyping / manual transcription", "Linux",
 "Read PII off the screen and type it into an unmonitored form. Expect nothing to catch this: record it as accepted residual risk rather than leaving the row blank.",
 "Differentiator"),
# ------------------------------------------------------------ NET
("P-N01.Windows", NET, "SMB / network share copy", "Windows",
 "Copy a sensitive file to an unapproved network share, including a share on a personal NAS. Confirm you can separate sanctioned from unsanctioned shares rather than blocking all network copy.",
 "Table stakes"),
("P-N01.macOS", NET, "SMB / network share copy", "macOS",
 "Copy a sensitive file to an unapproved network share, including a share on a personal NAS. Confirm you can separate sanctioned from unsanctioned shares rather than blocking all network copy.",
 "Advanced"),
("P-N01.Linux", NET, "SMB / network share copy", "Linux",
 "Copy a sensitive file to an unapproved network share, including a share on a personal NAS. Confirm you can separate sanctioned from unsanctioned shares rather than blocking all network copy.",
 "Advanced"),
("P-N02.Windows", NET, "RDP clipboard and drive redirection", "Windows",
 "Copy a file into an RDP session and onto a redirected local drive. Redirected USB devices can appear as network shares, which changes which rule fires - and confirm macOS parity rather than assuming it.",
 "Advanced"),
("P-N02.macOS", NET, "RDP clipboard and drive redirection", "macOS",
 "Copy a file into an RDP session and onto a redirected local drive. Redirected USB devices can appear as network shares, which changes which rule fires - and confirm macOS parity rather than assuming it.",
 "Differentiator"),
("P-N03.Windows", NET, "VDI / Citrix / AVD redirection", "Windows",
 "Repeat the clipboard, print, and USB tests inside a virtual desktop. Non-persistent VDI needs a specific onboarding method, so confirm the agent survives a pool refresh.",
 "Advanced"),
("P-N03.macOS", NET, "VDI / Citrix / AVD redirection", "macOS",
 "Repeat the clipboard, print, and USB tests inside a virtual desktop. Non-persistent VDI needs a specific onboarding method, so confirm the agent survives a pool refresh.",
 "Differentiator"),
("P-N03.Linux", NET, "VDI / Citrix / AVD redirection", "Linux",
 "Repeat the clipboard, print, and USB tests inside a virtual desktop. Non-persistent VDI needs a specific onboarding method, so confirm the agent survives a pool refresh.",
 "Differentiator"),
("P-N04.Windows", NET, "Virtual machine shared folders (VMware, Parallels, WSL)", "Windows",
 "Drag a sensitive file into a guest VM, and write to a WSL mount. The guest is usually unmanaged, and WSL writes bypass many Windows agents.",
 "Differentiator"),
("P-N04.macOS", NET, "Virtual machine shared folders (VMware, Parallels, WSL)", "macOS",
 "Drag a sensitive file into a guest VM, and write to a WSL mount. The guest is usually unmanaged, and WSL writes bypass many Windows agents.",
 "Differentiator"),
("P-N04.Linux", NET, "Virtual machine shared folders (VMware, Parallels, WSL)", "Linux",
 "Drag a sensitive file into a guest VM, and write to a WSL mount. The guest is usually unmanaged, and WSL writes bypass many Windows agents.",
 "Differentiator"),
("P-N05.Windows", NET, "Personal VPN or DNS-over-HTTPS", "Windows",
 "Turn on a consumer VPN app, then upload a file of sample PII to a personal cloud storage account. Any control that depends on network path or proxy inspection fails here - this is the test that separates endpoint DLP from network DLP.",
 "Table stakes"),
("P-N05.macOS", NET, "Personal VPN or DNS-over-HTTPS", "macOS",
 "Turn on a consumer VPN app, then upload a file of sample PII to a personal cloud storage account. Any control that depends on network path or proxy inspection fails here - this is the test that separates endpoint DLP from network DLP.",
 "Table stakes"),
("P-N05.Linux", NET, "Personal VPN or DNS-over-HTTPS", "Linux",
 "Turn on a consumer VPN app, then upload a file of sample PII to a personal cloud storage account. Any control that depends on network path or proxy inspection fails here - this is the test that separates endpoint DLP from network DLP.",
 "Advanced"),
("P-N06.Windows", NET, "Off-network / hotspot", "Windows",
 "Disconnect from the corporate network and Wi-Fi and tether the laptop to a phone. Then copy a sensitive file to a USB drive, and upload a second file to a personal cloud storage account. Confirm cached policy still enforces, and that events queue and upload when the device reconnects.",
 "Table stakes"),
("P-N06.macOS", NET, "Off-network / hotspot", "macOS",
 "Disconnect from the corporate network and Wi-Fi and tether the laptop to a phone. Then copy a sensitive file to a USB drive, and upload a second file to a personal cloud storage account. Confirm cached policy still enforces, and that events queue and upload when the device reconnects.",
 "Table stakes"),
("P-N06.Linux", NET, "Off-network / hotspot", "Linux",
 "Disconnect from the corporate network and Wi-Fi and tether the laptop to a phone. Then copy a sensitive file to a USB drive, and upload a second file to a personal cloud storage account. Confirm cached policy still enforces, and that events queue and upload when the device reconnects.",
 "Advanced"),
("P-N07.Windows", NET, "Fully offline enforcement", "Windows",
 "Disable networking entirely, create a NEW file containing 30 SSNs, and immediately attempt to copy it to a USB drive. A never-evaluated file is the hard case: where just-in-time protection exists it holds egress until evaluation completes, and it is frequently Windows-only.",
 "Differentiator"),
("P-N07.macOS", NET, "Fully offline enforcement", "macOS",
 "Disable networking entirely, create a NEW file containing 30 SSNs, and immediately attempt to copy it to a USB drive. A never-evaluated file is the hard case: where just-in-time protection exists it holds egress until evaluation completes, and it is frequently Windows-only.",
 "Differentiator"),
("P-N07.Linux", NET, "Fully offline enforcement", "Linux",
 "Disable networking entirely, create a NEW file containing 30 SSNs, and immediately attempt to copy it to a USB drive. A never-evaluated file is the hard case: where just-in-time protection exists it holds egress until evaluation completes, and it is frequently Windows-only.",
 "Differentiator"),
]
